### ISSUE TITLE
怎么调整分屏的窗口大小

### ISSUE THREAD

**Issue by zhiqiang21** [ruanyl/bigvim#14]
大哥哥，在 bigvim 的配置怎么调整分屏窗口的大小哇

**Comment by ruanyl** [comment]
@zhiqiang21 这个功能我平时用的少，但是vim自己的就有调整大小的功能。http://vim.wikia.com/wiki/Resize_splits_more_quickly

我一般都是使用<tab>最大化当前split窗口，完了再<tab>切换回来
