### ISSUE TITLE
没一行中这些高亮的光标有什么特殊意义么

### ISSUE THREAD

**Issue by zhiqiang21** [ruanyl/bigvim#15]
![qq20160113-0](https://cloud.githubusercontent.com/assets/3990411/12288380/e75d106e-ba0e-11e5-8e80-65376d1ed91e.png)
这一行的中单词高亮有什么作用么

**Comment by zhiqiang21** [comment]
![qq20160113-0](https://cloud.githubusercontent.com/assets/3990411/12288387/05344030-ba0f-11e5-8262-131cce6686fd.png)

**Comment by ruanyl** [comment]
[quick-scope](https://github.com/unblevable/quick-scope) 插件的。行内快速跳转。f+高亮字母，跳转到高亮字母处

**Comment by zhiqiang21** [comment]
好的谢谢啦
