### ISSUE TITLE
可否支持autoprefix

### ISSUE THREAD

**Issue by zhiqiang21** [ruanyl/bigvim#16]
可否添加插件和快捷键对 css 文件运行 autoprefix

**Comment by ruanyl** [comment]
其实是有想过加上autoprefix，但是觉得这一类的工作似乎应该交给gulp,grunt + postcss等这一类build工具来解决

**Comment by zhiqiang21** [comment]
有时候感觉有快捷键添加还是挺方便的

**Comment by ruanyl** [comment]
@zhiqiang21 不知道有多少这种使用场景，用postcss一般都是：
postcss --use autoprefix `src.css` -d `dest/` 就是说你编辑的是原css，但是实际使用的css是“compile”之后的。
有一个vim的autoprefix插件，你可以装上试试。
