### ISSUE TITLE
.vimrc无法修改了

### ISSUE THREAD

**Issue by zhubaobao** [ruanyl/bigvim#22]
装了之后，我无法修改原有的.vimrc文件。

**Comment by ruanyl** [comment]
你好，这个安装会在你的home目录建.vimrc的软链到本配置的vimrc. 无法修改具体是指什么？

**Comment by zhubaobao** [comment]
我home下没有.vimrc ，～目录下原有的.vimrc修改不了了

**Comment by ruanyl** [comment]
> ～目录下原有的.vimrc修改不了了

是指没了还是怎么回事？修改不了是指什么？

但是归根结底，你需要在你的~目录下有两个软链：
```
ln -s ~/.vimrc path/to/bigvim/vimrc
ln -s ~/.vim path/to/bigvim/
```
