### ISSUE TITLE
errors occured when using it in ubuntu 16.04

### ISSUE THREAD

**Issue by tengxianbing** [ruanyl/bigvim#24]
$vi
line   24:  E185: Cannot find color scheme 'molokai'

$vi .bigvim/vimrc.bundles
".bigvim/vimrc.bundles" 383L, 14505C
E117: Unknown function: fugitive#statusline
Press ENTER or type command to continue
E15: Invalid expression: fugitive#statusline()

**Comment by ruanyl** [comment]
Have you installed all the plugins? Looks like some plugins are missing.

**Comment by ruanyl** [comment]
I will close this issue for now, feel free to reopen.
