### ISSUE TITLE
`/`搜索之后报错

### ISSUE THREAD

**Issue by colorwin** [ruanyl/bigvim#26]
`/`搜索回车后会报错误, 按`enter` 继续后, 以后任何操作都还是会一直报这个错误:

系统ubuntu 16.04

```
E117: Unknown function: execute
E15: Invalid expression: execute('nohlsearch')[-1]
Press ENTER or type command to continue
```

**Comment by ruanyl** [comment]
默认`/`搜索是用vim-easymotion代替的，vim-easymotion能正常使用吗？

**Comment by colorwin** [comment]
使用 空格 搜索也就是 vim-easymotion 没问题.
我使用 / 搜索调用的还是vim原始的搜索不是 vim-easymotion 并且报错.

**Comment by ruanyl** [comment]
你把这两行去掉没？
https://github.com/ruanyl/bigvim/blob/master/vimrc.bundles#L228

**Comment by colorwin** [comment]
`[[` 这个操作会产生这个错误:

```
E486: Pattern not found: \(.*\%#\)\@!\_^\s*\zs\(\(abstract\s\+\|final\s\+\|private\s\+\|protected\s\+\|public\s\+\|static\s\+\)*function\|\(abstract\s\
+\|final\s\+\)*class\|interface\)
```

我想也许是我的安装有问题, 于是我打算重装一次

```
wget -qO- https://raw.githubusercontent.com/ruanyl/bigvim/master/install.sh | bash
```

然后报错了, [1]退出:

```
 Searching for invalid plugins in /home/ycs/.vim/bundle 
 Directories to delete:  
- /home/ycs/.vim/bundle/L9/                                                                                                                
 - /home/ycs/.vim/bundle/Vundle.vim/                                                                                                         
 - /home/ycs/.vim/bundle/command-t/                                                                                                            
 - /home/ycs/.vim/bundle/newL9/                                                                                                                
 - /home/ycs/.vim/bundle/sparkup/ 
```

我想可能是之前安装 Vundle 没安装好, 然后把这几个目录删掉了, 再重装一次, 没有错误.
然后 bigvim 所有功能正常使用了.
vim刚入门, 问题有点小白了, 谢谢作者的耐心解答.

**Comment by colorwin** [comment]
晕, 解决了`[[`的问题而已, `/`按回车后还是报错, 那两行我没删掉.

```
E117: Unknown function: execute
E15: Invalid expression: execute('nohlsearch')[-1]
Press ENTER or type command to continue
```

这个E117和E15在哪里找啊? 找了好久找不到, 也没写哪个文件

**Comment by colorwin** [comment]
所有和搜索有关的功能都报这个错误, 如 替换`:s`, `n`, `*`等都会.
可能是我之前设置 `:set nohlsearch` 和项目冲突了?

**Comment by ruanyl** [comment]
你有自定义的配置吗？你的安装步骤是怎么样的？重新运行下`:PlugInstall`看看

**Comment by colorwin** [comment]
我想铲掉项目重装一次试试, 然后好像删不干净, 重装不了...作者能出一行命令卸载吗?

**Comment by ruanyl** [comment]
直接删除~/.vim整个目录就行，所有东西都在里面。

**Comment by colorwin** [comment]
铲掉重装还是一样. 不是安装的问题
我把.vimrc文件的`set hlsearch`[这一行](https://github.com/ruanyl/bigvim/blob/master/vimrc#L56)注释掉就没有报错了, 如果这时`:set hls`就又报错. 应该是哪里调用了nohlsearch, 导致冲突了, 但是之前我并没有改过.vimrc文件.

**Comment by ruanyl** [comment]
我查了下，有几个地方和`set hlsearch` 可能会冲突
1. 默认的colorschema`gruvbox`，你可以换一个colorschema看看
2. `romainl/vim-cool`插件，注释掉看看

**Comment by colorwin** [comment]
是这个插件的问题：`romainl/vim-cool`.
注释掉就好了.
