### ISSUE TITLE
eslint --fix的问题

### ISSUE THREAD

**Issue by Kuohao-wu** [ruanyl/bigvim#27]
我装了eslint，经过配置，可以进行语法检查，但是每次修复都需要在vim中执行eslint --fix 的shell命令，这很不方便，求问，能不能再vimrc中设置shell命令，映射到一个快捷键上，或者保存即fix。

**Comment by ruanyl** [comment]
默认有`https://github.com/ruanyl/vim-fixmyjs`，你可以用`:Fixmyjs` 命令来自动修复，或者把这个命令映射到快捷键

**Comment by Kuohao-wu** [comment]
good，看漏了这个插件，谢谢。
