### ISSUE TITLE
tab缩进的修改

### ISSUE THREAD

**Issue by Kuohao-wu** [ruanyl/bigvim#28]
又来提一个issues...

```bash
autocmd FileType python set tabstop=4 shiftwidth=4 expandtab ai
autocmd FileType javascript,json,css,scss,html set tabstop=4 shiftwidth=4 expandtab ai
```
我想在html，scss，js里面将2个空格改成4个空格，遂在vimrc找到以下的选项，更改之后发现仍然是2个空格的缩进。source ~/.vimrc会报错。

但是我改上面的python的设置，改成2个空格，却有效，把所有的vimrc都看了一遍，实在不知道如何修改。

**Comment by ruanyl** [comment]
看看你的`HOME`有没有`.editorconfig` 文件，如果有这个文件，在这里配置。如果你的project根目录有`.editorconfig`， 那就默认会优先读取project根目录下的。

具体参考：https://github.com/ruanyl/bigvim/blob/master/others/editorconfig

**Comment by Kuohao-wu** [comment]
还有强制代码风格插件，很强势，学习了。。。
找到了，在others里面有一个editorconfig文件，修改了就好了
谢谢。
