### ISSUE TITLE
jsdoc not work in typescript files

### ISSUE THREAD

**Issue by yuanxj1024** [ruanyl/bigvim#31]
we're write js with Typescript.

when enter `,,d` the jsdoc plugins not work.

how can i fix this?

**Comment by ruanyl** [comment]
I just checked vim-jsdoc documentation, it should support typescript since v0.10.0
https://github.com/heavenshell/vim-jsdoc#typescript

And what do you mean jsdoc plugin doesn't work? Have you seen any errors?

**Comment by yuanxj1024** [comment]
@ruanyl   Thanks.

It's work now.

First I install tslint for global.

And I changed **.bigvim/vimrc.bundles** file like this: 
1.

`
let g:ale_linters = {
\   'javascript': ['eslint'],
\   'typescript': ['tslint', 'tsc'],
\}
`
2. 
`
autocmd FileType typescript nnoremap <Leader><Leader>d :JsDoc<CR>
`

**Comment by ruanyl** [comment]
@yuanxj1024 that's great 👍 I will make updates according to your comments, thanks!
