### ISSUE TITLE
YouCompleteMe有办法配置语义补全么

### ISSUE THREAD

**Issue by zhiqiang21** [ruanyl/bigvim#35]
类似于sublime这种，比如我在注释里写了一个单词，当我在其他地方打这个单词的前几个字母的时候会语义提示这个单词。目前我配置好的只是对一些语言的内置方法进行补全。

**Comment by ruanyl** [comment]
我记得是可以的，具体的你可以看看YCM的文档

**Comment by zhiqiang21** [comment]
看了文档后找到答案，主要是配置下面三个

let g:ycm_collect_identifiers_from_comments_and_strings = 1
let g:ycm_complete_in_strings = 1
let g:ycm_complete_in_comments = 1
